services:
  - type: web
    name: travel-planning-ai
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: bash .render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GEMINI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false