services:
  - type: web
    name: travel-planning-ai
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --no-reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GEMINI_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false